/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── YoungCreative Professional Design System ──────────
        'primary':                   '#ffb59c',
        'primary-container':         '#f26b3a',
        'on-primary':                '#5c1900',
        'on-primary-container':      '#571700',
        'primary-fixed':             '#ffdbd0',
        'primary-fixed-dim':         '#ffb59c',
        'on-primary-fixed':          '#390c00',
        'on-primary-fixed-variant':  '#832700',
        'inverse-primary':           '#a93705',
        'surface-tint':              '#ffb59c',

        'secondary':                 '#e0c298',
        'on-secondary':              '#402d0f',
        'secondary-container':       '#584323',
        'on-secondary-container':    '#ceb188',
        'secondary-fixed':           '#fedeb2',
        'secondary-fixed-dim':       '#e0c298',
        'on-secondary-fixed':        '#281800',
        'on-secondary-fixed-variant':'#584323',

        'tertiary':                  '#5dd5f8',
        'on-tertiary':               '#003642',
        'tertiary-container':        '#00a2c3',
        'on-tertiary-container':     '#00323e',
        'tertiary-fixed':            '#b3ebff',
        'tertiary-fixed-dim':        '#5dd5f8',
        'on-tertiary-fixed':         '#001f27',
        'on-tertiary-fixed-variant': '#004e5f',

        'error':                     '#ffb4ab',
        'on-error':                  '#690005',
        'error-container':           '#93000a',
        'on-error-container':        '#ffdad6',

        'background':                '#131313',
        'on-background':             '#e5e2e1',
        'surface':                   '#131313',
        'surface-dim':               '#131313',
        'surface-bright':            '#393939',
        'surface-dark':              '#242424',
        'surface-light':             '#FFFFFF',
        'surface-container-lowest':  '#0e0e0e',
        'surface-container-low':     '#1c1b1b',
        'surface-container':         '#201f1f',
        'surface-container-high':    '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant':           '#353534',
        'on-surface':                '#e5e2e1',
        'on-surface-variant':        '#e0c0b6',
        'inverse-surface':           '#e5e2e1',
        'inverse-on-surface':        '#313030',

        'outline':                   '#a78a81',
        'outline-variant':           '#58413a',
        'border-dark':               '#333333',
        'text-primary':              '#F3F4F6',
        'text-muted':                '#9CA3AF',
        'success':                   '#4CAF50',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',   // 2px — sharp utilitarian
        'sm':      '0.125rem',
        'md':      '0.25rem',    // 4px — standard
        'lg':      '0.25rem',
        'xl':      '0.5rem',
        '2xl':     '0.5rem',
        'full':    '0.75rem',
      },
      spacing: {
        'base':           '4px',
        'unit-1':         '0.25rem',
        'unit-2':         '0.5rem',
        'unit-4':         '1rem',
        'unit-8':         '2rem',
        'gutter':         '1px',
        'bento-gap':      '12px',
        'margin-mobile':  '16px',
        'margin-desktop': '24px',
      },
      fontFamily: {
        sans:          ['Plus Jakarta Sans', 'Inter', 'system-ui', 'sans-serif'],
        'display-lg':  ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg':     ['Plus Jakarta Sans', 'sans-serif'],
        'body-md':     ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm':    ['Inter', 'sans-serif'],
        'mono-label':  ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg':        ['48px', { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg':       ['32px', { lineHeight: '1.2',  letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile':['24px', { lineHeight: '1.2',  fontWeight: '600' }],
        'headline-md':       ['20px', { lineHeight: '1.4',  fontWeight: '500' }],
        'body-lg':           ['16px', { lineHeight: '1.6',  fontWeight: '400' }],
        'body-md':           ['14px', { lineHeight: '1.5',  fontWeight: '400' }],
        'label-sm':          ['12px', { lineHeight: '1.2',  letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-label':        ['11px', { lineHeight: '1',    letterSpacing: '0.02em', fontWeight: '500' }],
      },
      keyframes: {
        shimmer:  { '100%': { transform: 'translateX(200%)' } },
        'bounce-x': {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(250%)' },
        },
        'pulse-slow': {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.4' },
        },
      },
      animation: {
        shimmer:      'shimmer 1.5s infinite',
        'bounce-x':   'bounce-x 1.8s infinite alternate ease-in-out',
        'pulse-slow': 'pulse-slow 2s infinite',
      },
    },
  },
  plugins: [],
};
